version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: "dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh"
    command: npx nodemon index.js
    restart: always
    networks: 
      - node_network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: 
      - --innodb-use-native-aio=0
    container_name: db    
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # image: rafaincode/nginx:prod
    container_name: nginx
    networks:
      - node_network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node_network:
    driver: bridge